### PR TITLE
base: Fix for issue causing keyboard to display over input text in certain conditions.

### PR DESCRIPTION
**Pull request by lly-q**
Source comes from the reverse engineering of the February security update (sq1d.220205.003)of pixel6 model and had tested.
Fixed: Wechat keyboard cover chat viewGroup.
Signed-off-by: loserq <2650009628@qq.com>

### CODE REVIEW

**Review by AmeChanRain — APPROVED** [review]
Hang it. Need more test

**Comment by lly-q** [comment]
> Hang it. Need more test

Ok.

**Comment by hh2333** [comment]
Waiting for merge February ASB, a similar commit was added in the February patch.

Ref: https://cs.android.com/android/_/android/platform/frameworks/base/+/b52de33e3b3e2b4863341ff86262e17c97094bc1.

**Comment by AmeChanRain** [comment]
Upstream has fixed this issue. So what we need to do is to merge the new tag. Thanks for your contribution anyway.

Reference:
https://cs.android.com/android/_/android/platform/frameworks/base/+/b52de33e3b3e2b4863341ff86262e17c97094bc1

**Comment by lly-q** [comment]
Thank you.

**Pull request closed without merging**
